export const KAFKA_CLIENT = Symbol('KAFKA_CLIENT')
export const KAFKA_CLIENT_OPTIONS = Symbol('KAFKA_CLIENT_OPTIONS')
export const KAFKA_CONSUMER_CLIENT = Symbol('KAFKA_CONSUMER_CLIENT')
export const KAFKA_PRODUCER_CLIENT = Symbol('KAFKA_PRODUCER_CLIENT')
